apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.ApplicationName}}
spec:
  rules:
    - host: {{.Host}}
      http:
        paths:
          - backend:
              service:
                name: {{.ApplicationName}}
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{.Host}}
      secretName: {{.ApplicationName}}-tls

---