apiVersion: v1alpha1
kind: Cluster

metadata:
  # Name of the cluster
  name: tuuturu-prod
  # Associate following email with the cluster
  email: mail@tuuturu.org

spec:
  # Associate following domain with the cluster
  rootDomain: tuuturu.org

  #plugins:
  #  certBot: true
  #  grafana: true
  #  nginxIngressController: true
  #  prometheus: true
  #  vault: true
  #
