apiVersion: v1alpha1
kind: Environment

metadata:
  # Name of the environment
  name: example-prod
  # Associate following email with the environment
  email: mail@example.com

spec:
  # Specify desired cloud provider
  provider: linode
  # Associate following domain with the environment
  domain: example.com
  # Specify associated Infrastructure As Code (IAC) repository
  repository: git@github.com:example/infrastructure.git

  #users:
  #  - email: user@example.com

  #plugins:
  #  nginxIngressController: true
  #  certManager: true
  #  grafana: true
  #  prometheus: true
  #  loki: true
  #  argocd: true
