site_name: XCTL
site_url: https://tuuturu.github.io/xctl/
site_description: A tool for managing a Kubernetes and CNCF based infrastructure
site_author: Julius Pedersen

theme: material
repo_url: https://github.com/tuuturu/xctl
edit_uri: null

nav:
  - 'Getting started':
      - 'Create an environment': getting-started/apply-environment.md
      - 'Deploy an application': getting-started/apply-application.md
      - 'Delete an application': getting-started/delete-application.md
      - 'Delete an environment': getting-started/delete-environment.md
  - 'Environment':
      - 'Manifest reference': environment/manifest.md
