name: Deploy frontend

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.10.4
          cache: pip

      - name: Install dependencies
        working-directory: docs/frontend
        run: pip install -r requirements.txt

      - name: Build frontend
        working-directory: docs/frontend
        run: mkdocs build

      - name: GitHub Pages
        # You may pin to the exact commit or the version.
        uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        with:
          # Build directory to deploy
          build_dir: docs/frontend/site
          fqdn: ''# optional
